// <auto-generated />
namespace _201224_LinaButikPanel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class HomeSayfa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HomeSayfa));
        
        string IMigrationMetadata.Id
        {
            get { return "202101191234052_HomeSayfa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
